/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_mob41_osumer_daemon_OsumerOverlay */

#ifndef _Included_com_github_mob41_osumer_daemon_OsumerOverlay
#define _Included_com_github_mob41_osumer_daemon_OsumerOverlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_mob41_osumer_daemon_OsumerOverlay
 * Method:    startWithOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mob41_osumer_daemon_OsumerOverlay_startWithOverlay(JNIEnv *, jclass);

/*
 * Class:     com_github_mob41_osumer_daemon_OsumerOverlay
 * Method:    injectOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mob41_osumer_daemon_OsumerOverlay_injectOverlay(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
