/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_mob41_osumer_OsumerNative */

#ifndef _Included_com_github_mob41_osumer_OsumerNative
#define _Included_com_github_mob41_osumer_OsumerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_github_mob41_osumer_OsumerNative
* Method:    getProgramFiles
* Signature: ()Ljava.lang.String;
*/
JNIEXPORT jstring JNICALL Java_com_github_mob41_osumer_OsumerNative_getProgramFiles(JNIEnv *, jclass);

/*
 * Class:     com_github_mob41_osumer_OsumerNative
 * Method:    startWithOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mob41_osumer_OsumerNative_startWithOverlay(JNIEnv *, jclass);

/*
 * Class:     com_github_mob41_osumer_OsumerNative
 * Method:    injectOverlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mob41_osumer_OsumerNative_injectOverlay(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
